import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["selector", ":is(.dark, .aurora-dark, .swiss-dark)"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    borderRadius: {
      none: "0",
      sm: "0.5rem",
      DEFAULT: "0.75rem",
      md: "0.75rem",
      lg: "0.875rem",
      xl: "1rem",
      "2xl": "1.25rem",
      "3xl": "1.5rem",
      full: "9999px",
    },
    extend: {
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          '"SF Pro Text"',
          "var(--font-inter)",
          "Inter",
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        display: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          "var(--font-inter)",
          "Inter",
          "sans-serif",
        ],
        chrome: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        body: [
          "var(--font-source-sans-3)",
          '"Source Sans 3"',
          "system-ui",
          "sans-serif",
        ],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        obsidian: "var(--obsidian)",
        "trajectory-blue": "var(--trajectory-blue)",
        "atmospheric-grey": "var(--atmospheric-grey)",
        surface: {
          page: "var(--surface-page)",
          card: "var(--surface-card)",
          elevated: "var(--surface-elevated)",
          sidebar: "var(--surface-sidebar)",
          input: "var(--surface-input)",
          muted: "var(--surface-muted)",
        },
        border: {
          DEFAULT: "var(--border-subtle)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
          active: "var(--trajectory-blue)",
        },
        /* Semantic status tokens (pair with bg- / border- / text-) */
        status: {
          positive: "var(--status-positive-fg)",
          "positive-surface": "var(--status-positive-surface)",
          "positive-border": "var(--status-positive-border)",
          neutral: "var(--status-neutral-fg)",
          "neutral-surface": "var(--status-neutral-surface)",
          "neutral-border": "var(--status-neutral-border)",
          warning: "var(--status-warning-fg)",
          "warning-surface": "var(--status-warning-surface)",
          "warning-border": "var(--status-warning-border)",
          caution: "var(--status-caution-fg)",
          "caution-surface": "var(--status-caution-surface)",
          "caution-border": "var(--status-caution-border)",
          critical: "var(--status-critical-fg)",
          "critical-surface": "var(--status-critical-surface)",
          "critical-border": "var(--status-critical-border)",
        },
        badge: {
          "pending-bg": "#faf6ed",
          "pending-text": "#6a5030",
          "pending-ring": "#c9b078",
          "high-bg": "#faf5ef",
          "high-text": "#6a4528",
          "high-ring": "#b8926a",
          "critical-bg": "#faf0f0",
          "critical-text": "#6b3030",
          "critical-ring": "#b06060",
          "low-bg": "#f2f7ec",
          "low-text": "#3a5a24",
          "low-ring": "#8faa6a",
          "medium-bg": "#f3f4f8",
          "medium-text": "#3a4558",
          "medium-ring": "#909dad",
        },
        light: {
          "text-primary": "var(--text-primary)",
          "text-secondary": "var(--text-secondary)",
          "text-tertiary": "var(--text-tertiary)",
          "text-positive": "var(--status-positive-fg)",
          "text-warning": "var(--status-warning-fg)",
          "text-critical": "var(--status-critical-fg)",
          "text-nav": "#2e2e2e",
        },
        ref: {
          cta: "var(--ref-cta)",
          ice: "var(--ref-ice)",
          mint: "var(--ref-mint)",
        },
        nexus: {
          discovery: "var(--nexus-discovery)",
          "discovery-soft": "var(--nexus-discovery-soft)",
          "discovery-border": "var(--nexus-discovery-border)",
          intake: "var(--nexus-intake)",
          "intake-soft": "var(--nexus-intake-soft)",
          "intake-border": "var(--nexus-intake-border)",
          rescue: "var(--nexus-rescue)",
          "rescue-soft": "var(--nexus-rescue-soft)",
          "rescue-border": "var(--nexus-rescue-border)",
          approval: "var(--nexus-approval)",
          "approval-soft": "var(--nexus-approval-soft)",
          "approval-border": "var(--nexus-approval-border)",
          execution: "var(--nexus-execution)",
          "execution-soft": "var(--nexus-execution-soft)",
          "execution-border": "var(--nexus-execution-border)",
          growth: "var(--nexus-growth)",
          "growth-soft": "var(--nexus-growth-soft)",
          "growth-border": "var(--nexus-growth-border)",
        },
        apple: {
          text: "var(--apple-text)",
          "text-secondary": "var(--apple-text-secondary)",
          bg: "var(--apple-bg)",
          "bg-alt": "var(--apple-bg-alt)",
          accent: "var(--apple-accent)",
          "accent-hover": "var(--apple-accent-hover)",
          link: "var(--apple-link)",
          cinematic: "var(--apple-cinematic)",
        },
        selectable: {
          edge: "var(--selectable-card-border)",
          "edge-selected": "var(--selectable-card-border-selected)",
          "edge-hover": "var(--selectable-card-border-hover)",
        },
        glass: {
          DEFAULT: "var(--glass-bg)",
          border: "var(--glass-border)",
          input: "var(--glass-input-bg)",
          sidebar: "var(--app-sidebar-bg)",
        },
      },
      boxShadow: {
        "glow-positive": "none",
        "glow-critical": "none",
        "card-halo": "0 1px 2px rgba(0, 0, 0, 0.12)",
        "card-halo-light": "0 1px 2px rgba(0, 0, 0, 0.04)",
      },
      letterSpacing: {
        tightest: "-0.02em",
        brand: "0.18em",
      },
      transitionDuration: {
        interaction: "200ms",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDownRow: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseDot: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.45", transform: "scale(0.92)" },
        },
      },
      animation: {
        "fade-up": "fadeUp 0.55s ease-out both",
        "slide-down-row": "slideDownRow 0.45s ease-out both",
        "pulse-dot": "pulseDot 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;
